### ISSUE TITLE
Automatic type compilation ? typescript -> io-ts

### ISSUE THREAD

**Issue by magicaltoast** [gcanti/io-ts#516] opened 2020-09-04 14:09 UTC
Hi, I am wondering if it is possible to automatically compile typescript types to io-ts.
I searched the documentation and I couldn't find anything like this.

I just basically want to check in runtime if an object is a type that I declared.
Can I do it just using typescript type or I must write it io-ts way.

Sorry if this a trivial question but the documentation of this project is confusing for me and examples aren't meaningful for me.

If it isn't possible it would be a cool feature :) 

Have a great day, thanks in advance for any help.

PS. please don't be rough, I know that this could be a extremely trivial question, but i couldn't find a answer in docs

**Comment by cyberixae** [comment] 2020-09-04 18:11
TypeScript types can be inferred from io-ts codecs but not the other way round. However, io-ts codecs can be generated from different formats using [io-ts-codegen](https://github.com/gcanti/io-ts-codegen). For example I wrote a tool called [io-ts-from-json-schema](https://github.com/maasglobal/io-ts-from-json-schema) that uses io-ts-codegen to generate io-ts codecs from json schema definitions.

**Comment by cyberixae** [comment] 2020-09-04 18:19
@magicaltoast Here you can see all packages that depend on io-ts-codegen https://www.npmjs.com/browse/depended/io-ts-codegen

**Comment by schickling** [comment] 2020-11-12 14:42
This issue seems to be a duplicate of #318 and maybe should be closed?

Seems like https://github.com/juusaw/ts-to-io is what you're looking for.

**Closed** 2020-11-12 14:45 UTC
Labels: duplicate
